### ISSUE TITLE
Could we simplify making AWS API calls with paging?

### ISSUE THREAD

**Issue by ina-stoyanova** [gruntwork-io/cloud-nuke#226]
**Context:** 
In quite a few of our `aws` functions we have to make a batched call into AWS API to get some data (E.g. `s3` module & `dynamodb`, and others). 

**Question:** Is it possible to extract this logic somehow? E.g. so not every module has to figure out how to paging and batch calls on its own?

**Comment by hongil0316** [comment]
For any future resources we implement, we can leverage the pages get calls to handle pagination, instead of having our own batching logic. A lot of the resources already use this API for that. 

Closing this issue since this is no longer relevant - may not make sense to make this change to all existing resources.
