### ISSUE TITLE
Exclusion support for SQS?

### ISSUE THREAD

**Issue by chrisswanda** [gruntwork-io/cloud-nuke#360]
I created an config/exclusion file to for SQS, so that I can keep SQS during a nuke session of my sandbox account.

```sqs:
  include:
  exclude:
    names_regex:
      - Sandbox
```
When I run `cloud-nuke aws --resource-type sqs --region us-east-2 --config sandbox_exclusion.yml --dry-run` it still identifies SQS that are to be nuked. Are SQS topics supported for config files?

I'm on `cloud-nuke version v0.19.0`

**Comment by zackproser** [comment]
Hi @chrisswanda, 

We don't currently support config file exclusion or inclusion for SQS. You can check by looking at the table in the cloud-nuke README under the "What's supported?" header - SQS is unfortunately current supported. 

One of the reasons is that, for SQS, retrieving the attributes for a given queue is a separate operation from listing the queues themselves. 

This means that we'd need to potentially make double the API calls in order to be able to support this functionality for SQS, which needs to be balanced against the likelihood that AWS will rate limit cloud-nuke for making too many requests simultaneously. This would likely get worse the more resources you were running cloud-nuke against. 

All that said, pull requests to deal with these issues are very welcome!

**Comment by Avinashanakal** [comment]
hey @zackproser i am interested in working on this understood the problem
in order contribute do i need to raise RFC or is it fine since the issue has been already raised

**Comment by hongil0316** [comment]
No longer relevant. It supports exclusion with config file.
