### ISSUE TITLE
Factory reset instead of nuke

### ISSUE THREAD

**Issue by dw61** [gruntwork-io/cloud-nuke#366]
Based on README, I don't see an option to **factory reset** (instead of **nuke**) my account, i.e. don't remove default vpc, gateways, network ACLs, which comes with my account when I signed up. Is this what `cloud-nuke aws` does? Need clarification.
> this tool is HIGHLY DESTRUCTIVE and deletes **all** resources

**Comment by gostega** [comment]
Might be easier just to create a new account?

**Comment by dw61** [comment]
I got free AWS credits that comes with my account. I think I ended up nuking and created a new default VPC.

**Comment by ellisonc** [comment]
AWS makes it easy to [re-create](https://docs.aws.amazon.com/vpc/latest/userguide/default-vpc.html#create-default-vpc) the default vpc using the console or cli.  cloud-nuke does not currently support doing this programmatically. We at gruntwork tend to use this tool to clean up unused resources rather than create accounts that are in the default state. However, if there's enough interest in this feature it may be worth implementing with a cli flag as it shouldn't be too difficult.  I'll leave this open as a feature request for now. We'd welcome a PR if you have time. Thanks for your feedback!

**Comment by hongil0316** [comment]
Closing this issue as we haven't seen any other interest in this feature for longer than 6 months.
