### ISSUE TITLE
Delete S3 buckets older than t time

### ISSUE THREAD

**Issue by include** [gruntwork-io/cloud-nuke#58]
It would be fun to have this option too. We have a couple of labs accounts so... you see...

Thanks in advance,
F

**Comment by lasseoe** [comment]
I mostly have this working, however there's a small annoying thing. If I simply duplicate ami.go and change it to handle S3 buckets, it will list all buckets again and again as we iterate through regions. It does this because there's no way to only list buckets within a region.  I can call GetBucketLocation and get the region for each bucket so we can use it to exclude regions, of course doubling the amount of API calls.

There are, as I see it, two solutions.
1) Use the above approach and be fine with issuing a silly amount of redundant API calls, going through i.e. 75 buckets and 8 regions would yield 75*8 api calls. 
2) Treat S3 differently, this would mean changing quite a few things I would imagine, and I have no idea how you'd want this implemented.

If solution 1 is what is preferred, then I will submit a PR within the next few days.

**Comment by brikis98** [comment]
How about building a local cache? 

Each time `getAllS3Buckets` is called:

1. Check if the cache contains buckets.
1. If it does, return the buckets for that region.
1. If it does not:
    1. Fetch all bucket names.
    1. Loop through and get the bucket location once for each bucket name.
    1. Put it all into a cache (i.e., a `map` of lists) broken down by region name.
    1. Return the list of buckets for the currently requested region.

This would require 75+1 API calls for 75 buckets, but there's no working around that.

**Comment by lasseoe** [comment]
Great suggestion, for some reason that didn't occur to me as an option, but it's pretty logical, thanks!
I'll submit a PR once I have this working :)

**Comment by davidvasandani** [comment]
@lasseoe have you made any progress on this PR? We got bit by something similar and would love to have S3 added to CloudNuke.

**Comment by saurabh-hirani** [comment]
@brikis98 @davidvasandani raised https://github.com/gruntwork-io/cloud-nuke/issues/58 to support S3 bucket deletion.

**Comment by yorinasub17** [comment]
This is now released in https://github.com/gruntwork-io/cloud-nuke/releases/tag/v0.1.17
