### ISSUE TITLE
Add dry-run mode

### ISSUE THREAD

**Issue by asyd** [gruntwork-io/cloud-nuke#75]
Hi, 

as you mentioned on #30 you should add a `--dry-run` mode.

I must confess I switch to `awseeper` because dry mode is missing

Regards

**Comment by yorinasub17** [comment]
Dry run mode sounds like a good feature to add.

With that said, we are unlikely to get to this any time soon since we typically use `cloud-nuke` in CI environments so `--dry-run` isn't necessary for us and we are buried at the moment with other priorities.

In the mean time, we would be happy to review any PRs if anyone needs this and is willing to contribute!

**Comment by saurabh-hirani** [comment]
@yorinasub17 @asyd raised PR for dry run https://github.com/gruntwork-io/cloud-nuke/pull/78

**Comment by saurabh-hirani** [comment]
@yorinasub17 This can be closed as dry run mode was added in above commit and released as per https://github.com/gruntwork-io/cloud-nuke/releases/tag/v0.1.12 by @autero1

**Comment by robmorgan** [comment]
Thanks @saurabh-hirani, closing due to https://github.com/gruntwork-io/cloud-nuke/releases/tag/v0.1.12
